/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Application.LiveStorage;
import Travel.Trip.Trip;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;

/**
 *
 * @author localadmin
 */
public class TripsPanel extends javax.swing.JPanel {

    /**
     * Creates new form TripsPanel
     */
    public TripsPanel() {
        this.setLayout(new BoxLayout(this, BoxLayout.PAGE_AXIS));
        LiveStorage ls = LiveStorage.getInstance();
        List<Trip> trips = ls.getTrips();
        for (Trip trip : trips) {
            String s = ""+trip.getBasePrice()+"$"+", de "+trip.getDepartureLocation()+" vers "+trip.getArrivalLocation()+
                    ", départ à "+trip.getDepartureDateTime()+" et arrivée à "+trip.getArrivalTime()+", id:"+trip.getId()+
                    ", compagnie:"+trip.getCompany();
            JLabel l = new JLabel(s);
            this.add(l);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
