/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.AdminUI;

import javax.swing.JDialog;
import javax.swing.JFrame;

import Sessions.Admin.AdminSession;
import Travel.TravelType;
import UI.UserFrame;

/**
 *
 * @author localadmin
 */
public class AdminFrame extends UserFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        super();
    }
    public AdminFrame(String adminID) {
		super(adminID);
                userSession = new AdminSession(adminID);
		this.setTitle("ADMIN SESSION");
		this.setSize(400,200);
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.setLocationRelativeTo(null);
                initComponents();
		this.setVisible(true);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        TabbedTravel = new javax.swing.JTabbedPane();
        panelPlane = new javax.swing.JPanel();
        lPlane = new javax.swing.JLabel();
        lAirport = new javax.swing.JLabel();
        lFlight = new javax.swing.JLabel();
        lFlightCompany = new javax.swing.JLabel();
        bAddPlane = new javax.swing.JButton();
        bAddAirport = new javax.swing.JButton();
        bAddFlight = new javax.swing.JButton();
        bAddFlightCompany = new javax.swing.JButton();
        bDeletePlane = new javax.swing.JButton();
        bDeleteAirport = new javax.swing.JButton();
        bDeleteFlight = new javax.swing.JButton();
        bDeleteFlightCompany = new javax.swing.JButton();
        bEditPlane = new javax.swing.JButton();
        bEditAirport = new javax.swing.JButton();
        bEditFlight = new javax.swing.JButton();
        bEditFlightCompany = new javax.swing.JButton();
        assignPricePlane = new javax.swing.JButton();
        bShowFlights = new javax.swing.JButton();
        panelTrain = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bAddTrain = new javax.swing.JButton();
        bAddTrainStation = new javax.swing.JButton();
        bAddLine = new javax.swing.JButton();
        bAddTrainCompany = new javax.swing.JButton();
        bDeleteTrain = new javax.swing.JButton();
        bDeleteTrainStation = new javax.swing.JButton();
        bDeleteLine = new javax.swing.JButton();
        bDeleteTrainCompany = new javax.swing.JButton();
        bEditTrain = new javax.swing.JButton();
        bEditTrainStation = new javax.swing.JButton();
        bEditLine = new javax.swing.JButton();
        bEditTrainCompany = new javax.swing.JButton();
        assignPriceTrain = new javax.swing.JButton();
        bShowItineries = new javax.swing.JButton();
        panelCruise = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bAddCruiser = new javax.swing.JButton();
        bAddPort = new javax.swing.JButton();
        bAddCruise = new javax.swing.JButton();
        bAddCruiseCompany = new javax.swing.JButton();
        bDeleteCruiser = new javax.swing.JButton();
        bDeletePort = new javax.swing.JButton();
        bDeleteCruise = new javax.swing.JButton();
        bDeleteCruiseCompany = new javax.swing.JButton();
        bEditCruiser = new javax.swing.JButton();
        bEditPort = new javax.swing.JButton();
        bEditCruise = new javax.swing.JButton();
        bEditCruiseCompany = new javax.swing.JButton();
        assignPriceCruise = new javax.swing.JButton();
        bShowCruises = new javax.swing.JButton();

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lPlane.setText("Avion");

        lAirport.setText("Aéroport");

        lFlight.setText("Vol");

        lFlightCompany.setText("Compagnie aérienne");

        bAddPlane.setText("+");
        bAddPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddPlaneActionPerformed(evt);
            }
        });

        bAddAirport.setText("+");
        bAddAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddAirportActionPerformed(evt);
            }
        });

        bAddFlight.setText("+");
        bAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddFlightActionPerformed(evt);
            }
        });

        bAddFlightCompany.setText("+");
        bAddFlightCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddFlightCompanyActionPerformed(evt);
            }
        });

        bDeletePlane.setText("-");
        bDeletePlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletePlaneActionPerformed(evt);
            }
        });

        bDeleteAirport.setText("-");
        bDeleteAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteAirportActionPerformed(evt);
            }
        });

        bDeleteFlight.setText("-");
        bDeleteFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteFlightActionPerformed(evt);
            }
        });

        bDeleteFlightCompany.setText("-");
        bDeleteFlightCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteFlightCompanyActionPerformed(evt);
            }
        });

        bEditPlane.setText("Edit");
        bEditPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditPlaneActionPerformed(evt);
            }
        });

        bEditAirport.setText("Edit");
        bEditAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditAirportActionPerformed(evt);
            }
        });

        bEditFlight.setText("Edit");
        bEditFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditFlightActionPerformed(evt);
            }
        });

        bEditFlightCompany.setText("Edit");
        bEditFlightCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditFlightCompanyActionPerformed(evt);
            }
        });

        assignPricePlane.setText("Assigner des prix");
        assignPricePlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignPricePlaneActionPerformed(evt);
            }
        });

        bShowFlights.setText("Consulter les vols");
        bShowFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowFlightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPlaneLayout = new javax.swing.GroupLayout(panelPlane);
        panelPlane.setLayout(panelPlaneLayout);
        panelPlaneLayout.setHorizontalGroup(
            panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPlaneLayout.createSequentialGroup()
                        .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPlane)
                            .addComponent(lAirport)
                            .addComponent(lFlight)
                            .addComponent(lFlightCompany))
                        .addGap(31, 31, 31)
                        .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPlaneLayout.createSequentialGroup()
                                .addComponent(bAddFlight)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteFlight)
                                .addGap(18, 18, 18)
                                .addComponent(bEditFlight))
                            .addGroup(panelPlaneLayout.createSequentialGroup()
                                .addComponent(bAddAirport)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteAirport)
                                .addGap(18, 18, 18)
                                .addComponent(bEditAirport))
                            .addGroup(panelPlaneLayout.createSequentialGroup()
                                .addComponent(bAddPlane)
                                .addGap(18, 18, 18)
                                .addComponent(bDeletePlane)
                                .addGap(18, 18, 18)
                                .addComponent(bEditPlane))
                            .addGroup(panelPlaneLayout.createSequentialGroup()
                                .addComponent(bAddFlightCompany)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteFlightCompany)
                                .addGap(18, 18, 18)
                                .addComponent(bEditFlightCompany))))
                    .addGroup(panelPlaneLayout.createSequentialGroup()
                        .addComponent(assignPricePlane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bShowFlights)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panelPlaneLayout.setVerticalGroup(
            panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlaneLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPlane)
                    .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddPlane)
                        .addComponent(bDeletePlane)
                        .addComponent(bEditPlane)))
                .addGap(18, 18, 18)
                .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAirport)
                    .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddAirport)
                        .addComponent(bDeleteAirport)
                        .addComponent(bEditAirport)))
                .addGap(18, 18, 18)
                .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFlight)
                    .addComponent(bAddFlight)
                    .addComponent(bDeleteFlight)
                    .addComponent(bEditFlight))
                .addGap(10, 10, 10)
                .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFlightCompany)
                    .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddFlightCompany)
                        .addComponent(bDeleteFlightCompany)
                        .addComponent(bEditFlightCompany)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panelPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignPricePlane)
                    .addComponent(bShowFlights))
                .addContainerGap())
        );

        TabbedTravel.addTab("Avions", panelPlane);

        jLabel5.setText("Train");

        jLabel6.setText("Gare");

        jLabel7.setText("Itinéraire");

        jLabel8.setText("Compagnie ferroviaire");

        bAddTrain.setText("+");
        bAddTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddTrainActionPerformed(evt);
            }
        });

        bAddTrainStation.setText("+");
        bAddTrainStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddTrainStationActionPerformed(evt);
            }
        });

        bAddLine.setText("+");
        bAddLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddLineActionPerformed(evt);
            }
        });

        bAddTrainCompany.setText("+");
        bAddTrainCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddTrainCompanyActionPerformed(evt);
            }
        });

        bDeleteTrain.setText("-");
        bDeleteTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteTrainActionPerformed(evt);
            }
        });

        bDeleteTrainStation.setText("-");
        bDeleteTrainStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteTrainStationActionPerformed(evt);
            }
        });

        bDeleteLine.setText("-");
        bDeleteLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteLineActionPerformed(evt);
            }
        });

        bDeleteTrainCompany.setText("-");
        bDeleteTrainCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteTrainCompanyActionPerformed(evt);
            }
        });

        bEditTrain.setText("Edit");
        bEditTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditTrainActionPerformed(evt);
            }
        });

        bEditTrainStation.setText("Edit");
        bEditTrainStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditTrainStationActionPerformed(evt);
            }
        });

        bEditLine.setText("Edit");
        bEditLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditLineActionPerformed(evt);
            }
        });

        bEditTrainCompany.setText("Edit");
        bEditTrainCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditTrainCompanyActionPerformed(evt);
            }
        });

        assignPriceTrain.setText("Assigner des prix");
        assignPriceTrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignPriceTrainActionPerformed(evt);
            }
        });

        bShowItineries.setText("Consulter les lignes");
        bShowItineries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowItineriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTrainLayout = new javax.swing.GroupLayout(panelTrain);
        panelTrain.setLayout(panelTrainLayout);
        panelTrainLayout.setHorizontalGroup(
            panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTrainLayout.createSequentialGroup()
                        .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTrainLayout.createSequentialGroup()
                                .addComponent(bAddTrainCompany)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteTrainCompany)
                                .addGap(18, 18, 18)
                                .addComponent(bEditTrainCompany))
                            .addGroup(panelTrainLayout.createSequentialGroup()
                                .addComponent(bAddLine)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteLine)
                                .addGap(18, 18, 18)
                                .addComponent(bEditLine))
                            .addGroup(panelTrainLayout.createSequentialGroup()
                                .addComponent(bAddTrainStation)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteTrainStation)
                                .addGap(18, 18, 18)
                                .addComponent(bEditTrainStation))
                            .addGroup(panelTrainLayout.createSequentialGroup()
                                .addComponent(bAddTrain)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteTrain)
                                .addGap(18, 18, 18)
                                .addComponent(bEditTrain))))
                    .addGroup(panelTrainLayout.createSequentialGroup()
                        .addComponent(assignPriceTrain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bShowItineries)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panelTrainLayout.setVerticalGroup(
            panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrainLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddTrain)
                        .addComponent(bDeleteTrain)
                        .addComponent(bEditTrain)))
                .addGap(18, 18, 18)
                .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddTrainStation)
                        .addComponent(bDeleteTrainStation)
                        .addComponent(bEditTrainStation)))
                .addGap(18, 18, 18)
                .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bAddLine)
                    .addComponent(bDeleteLine)
                    .addComponent(bEditLine))
                .addGap(10, 10, 10)
                .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddTrainCompany)
                        .addComponent(bDeleteTrainCompany)
                        .addComponent(bEditTrainCompany)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panelTrainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignPriceTrain)
                    .addComponent(bShowItineries))
                .addContainerGap())
        );

        TabbedTravel.addTab("Trains", panelTrain);

        jLabel9.setText("Paquebot");

        jLabel10.setText("Port");

        jLabel11.setText("Croisière");

        jLabel12.setText("Compagnie maritime");

        bAddCruiser.setText("+");
        bAddCruiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddCruiserActionPerformed(evt);
            }
        });

        bAddPort.setText("+");
        bAddPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddPortActionPerformed(evt);
            }
        });

        bAddCruise.setText("+");
        bAddCruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddCruiseActionPerformed(evt);
            }
        });

        bAddCruiseCompany.setText("+");
        bAddCruiseCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddCruiseCompanyActionPerformed(evt);
            }
        });

        bDeleteCruiser.setText("-");
        bDeleteCruiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteCruiserActionPerformed(evt);
            }
        });

        bDeletePort.setText("-");
        bDeletePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeletePortActionPerformed(evt);
            }
        });

        bDeleteCruise.setText("-");
        bDeleteCruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteCruiseActionPerformed(evt);
            }
        });

        bDeleteCruiseCompany.setText("-");
        bDeleteCruiseCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteCruiseCompanyActionPerformed(evt);
            }
        });

        bEditCruiser.setText("Edit");
        bEditCruiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditCruiserActionPerformed(evt);
            }
        });

        bEditPort.setText("Edit");
        bEditPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditPortActionPerformed(evt);
            }
        });

        bEditCruise.setText("Edit");
        bEditCruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditCruiseActionPerformed(evt);
            }
        });

        bEditCruiseCompany.setText("Edit");
        bEditCruiseCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditCruiseCompanyActionPerformed(evt);
            }
        });

        assignPriceCruise.setText("Assigner des prix");
        assignPriceCruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignPriceCruiseActionPerformed(evt);
            }
        });

        bShowCruises.setText("Consulter les destinations");
        bShowCruises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowCruisesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCruiseLayout = new javax.swing.GroupLayout(panelCruise);
        panelCruise.setLayout(panelCruiseLayout);
        panelCruiseLayout.setHorizontalGroup(
            panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCruiseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCruiseLayout.createSequentialGroup()
                        .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(31, 31, 31)
                        .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCruiseLayout.createSequentialGroup()
                                .addComponent(bAddCruiseCompany)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteCruiseCompany)
                                .addGap(18, 18, 18)
                                .addComponent(bEditCruiseCompany))
                            .addGroup(panelCruiseLayout.createSequentialGroup()
                                .addComponent(bAddCruise)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteCruise)
                                .addGap(18, 18, 18)
                                .addComponent(bEditCruise))
                            .addGroup(panelCruiseLayout.createSequentialGroup()
                                .addComponent(bAddPort)
                                .addGap(18, 18, 18)
                                .addComponent(bDeletePort)
                                .addGap(18, 18, 18)
                                .addComponent(bEditPort))
                            .addGroup(panelCruiseLayout.createSequentialGroup()
                                .addComponent(bAddCruiser)
                                .addGap(18, 18, 18)
                                .addComponent(bDeleteCruiser)
                                .addGap(18, 18, 18)
                                .addComponent(bEditCruiser))))
                    .addGroup(panelCruiseLayout.createSequentialGroup()
                        .addComponent(assignPriceCruise)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bShowCruises)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        panelCruiseLayout.setVerticalGroup(
            panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCruiseLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddCruiser)
                        .addComponent(bDeleteCruiser)
                        .addComponent(bEditCruiser)))
                .addGap(18, 18, 18)
                .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddPort)
                        .addComponent(bDeletePort)
                        .addComponent(bEditPort)))
                .addGap(18, 18, 18)
                .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bAddCruise)
                    .addComponent(bDeleteCruise)
                    .addComponent(bEditCruise))
                .addGap(10, 10, 10)
                .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAddCruiseCompany)
                        .addComponent(bDeleteCruiseCompany)
                        .addComponent(bEditCruiseCompany)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(panelCruiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignPriceCruise)
                    .addComponent(bShowCruises))
                .addContainerGap())
        );

        TabbedTravel.addTab("Croisières", panelCruise);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedTravel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedTravel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void bAddCruiseCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddCruiseCompanyActionPerformed
        JDialog d = new AddCompanyDialog("Cruise", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddCruiseCompanyActionPerformed

    private void bAddCruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddCruiseActionPerformed
        JDialog d = new AddTripDialog("Cruise", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddCruiseActionPerformed

    private void bAddPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddPortActionPerformed
        JDialog d = new AddFacilityDialog("Cruise", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddPortActionPerformed

    private void bAddCruiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddCruiserActionPerformed
        JDialog d = new AddVehicleDialog("Cruise", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddCruiserActionPerformed

    private void bAddTrainCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddTrainCompanyActionPerformed
        JDialog d = new AddCompanyDialog("Train", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddTrainCompanyActionPerformed

    private void bAddLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddLineActionPerformed
        JDialog d = new AddTripDialog("Train", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddLineActionPerformed

    private void bAddTrainStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddTrainStationActionPerformed
        JDialog d = new AddFacilityDialog("Train", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddTrainStationActionPerformed

    private void bAddTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddTrainActionPerformed
        JDialog d = new AddVehicleDialog("Train", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddTrainActionPerformed

    private void bAddFlightCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddFlightCompanyActionPerformed
        JDialog d = new AddCompanyDialog("Plane", userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddFlightCompanyActionPerformed

    private void bAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddFlightActionPerformed
       JDialog d = new AddTripDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddFlightActionPerformed

    private void bAddAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddAirportActionPerformed
       JDialog d = new AddFacilityDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddAirportActionPerformed

    private void bAddPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddPlaneActionPerformed
        JDialog d = new AddVehicleDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bAddPlaneActionPerformed

    private void bEditFlightCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditFlightCompanyActionPerformed
        JDialog d = new EditCompanyDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditFlightCompanyActionPerformed

    private void bDeletePlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletePlaneActionPerformed
        JDialog d = new DeleteVehicleDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeletePlaneActionPerformed

    private void bDeleteAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteAirportActionPerformed
        JDialog d = new DeleteFacilityDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteAirportActionPerformed

    private void bDeleteFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteFlightActionPerformed
        JDialog d = new DeleteTripDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteFlightActionPerformed

    private void bDeleteFlightCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteFlightCompanyActionPerformed
        JDialog d = new DeleteCompanyDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteFlightCompanyActionPerformed

    private void bEditPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditPlaneActionPerformed
        JDialog d = new EditVehicleDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditPlaneActionPerformed

    private void bEditAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditAirportActionPerformed
        JDialog d = new EditFacilityDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditAirportActionPerformed

    private void bEditFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditFlightActionPerformed
        JDialog d = new EditTripDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditFlightActionPerformed

    private void assignPricePlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignPricePlaneActionPerformed
        JDialog d = new AssignPriceDialog("Plane",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_assignPricePlaneActionPerformed

    private void bShowFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowFlightsActionPerformed
        // TODO add TripsPanel to dialog
        ShowTripsDialog d = new ShowTripsDialog(TravelType.Plane,userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bShowFlightsActionPerformed

    private void bDeleteTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteTrainActionPerformed
        JDialog d = new DeleteVehicleDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteTrainActionPerformed

    private void bDeleteTrainStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteTrainStationActionPerformed
        JDialog d = new DeleteFacilityDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteTrainStationActionPerformed

    private void bDeleteLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteLineActionPerformed
        JDialog d = new DeleteTripDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteLineActionPerformed

    private void bDeleteTrainCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteTrainCompanyActionPerformed
        JDialog d = new DeleteCompanyDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteTrainCompanyActionPerformed

    private void bEditTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditTrainActionPerformed
        JDialog d = new EditVehicleDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditTrainActionPerformed

    private void bEditTrainStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditTrainStationActionPerformed
        JDialog d = new EditFacilityDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditTrainStationActionPerformed

    private void bEditLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditLineActionPerformed
        JDialog d = new EditTripDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditLineActionPerformed

    private void bEditTrainCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditTrainCompanyActionPerformed
        JDialog d = new EditCompanyDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditTrainCompanyActionPerformed

    private void assignPriceTrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignPriceTrainActionPerformed
        JDialog d = new AssignPriceDialog("Train",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_assignPriceTrainActionPerformed

    private void bShowItineriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowItineriesActionPerformed
        // TODO add TripsPanel to dialog
        ShowTripsDialog d = new ShowTripsDialog(TravelType.Train,userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bShowItineriesActionPerformed

    private void bDeleteCruiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteCruiserActionPerformed
        JDialog d = new DeleteVehicleDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteCruiserActionPerformed

    private void bDeletePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeletePortActionPerformed
        JDialog d = new DeleteFacilityDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeletePortActionPerformed

    private void bDeleteCruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteCruiseActionPerformed
        JDialog d = new DeleteTripDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteCruiseActionPerformed

    private void bDeleteCruiseCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteCruiseCompanyActionPerformed
        JDialog d = new DeleteCompanyDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bDeleteCruiseCompanyActionPerformed

    private void bEditCruiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditCruiserActionPerformed
        JDialog d = new EditVehicleDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditCruiserActionPerformed

    private void bEditPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditPortActionPerformed
        JDialog d = new EditFacilityDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditPortActionPerformed

    private void bEditCruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditCruiseActionPerformed
        JDialog d = new EditTripDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditCruiseActionPerformed

    private void bEditCruiseCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditCruiseCompanyActionPerformed
        JDialog d = new EditCompanyDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bEditCruiseCompanyActionPerformed

    private void assignPriceCruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignPriceCruiseActionPerformed
        JDialog d = new AssignPriceDialog("Cruise",userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_assignPriceCruiseActionPerformed

    private void bShowCruisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowCruisesActionPerformed
        // TODO add TripsPanel to dialog
        ShowTripsDialog d = new ShowTripsDialog(TravelType.Cruise,userSession);
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_bShowCruisesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedTravel;
    private javax.swing.JButton assignPriceCruise;
    private javax.swing.JButton assignPricePlane;
    private javax.swing.JButton assignPriceTrain;
    private javax.swing.JButton bAddAirport;
    private javax.swing.JButton bAddCruise;
    private javax.swing.JButton bAddCruiseCompany;
    private javax.swing.JButton bAddCruiser;
    private javax.swing.JButton bAddFlight;
    private javax.swing.JButton bAddFlightCompany;
    private javax.swing.JButton bAddLine;
    private javax.swing.JButton bAddPlane;
    private javax.swing.JButton bAddPort;
    private javax.swing.JButton bAddTrain;
    private javax.swing.JButton bAddTrainCompany;
    private javax.swing.JButton bAddTrainStation;
    private javax.swing.JButton bDeleteAirport;
    private javax.swing.JButton bDeleteCruise;
    private javax.swing.JButton bDeleteCruiseCompany;
    private javax.swing.JButton bDeleteCruiser;
    private javax.swing.JButton bDeleteFlight;
    private javax.swing.JButton bDeleteFlightCompany;
    private javax.swing.JButton bDeleteLine;
    private javax.swing.JButton bDeletePlane;
    private javax.swing.JButton bDeletePort;
    private javax.swing.JButton bDeleteTrain;
    private javax.swing.JButton bDeleteTrainCompany;
    private javax.swing.JButton bDeleteTrainStation;
    private javax.swing.JButton bEditAirport;
    private javax.swing.JButton bEditCruise;
    private javax.swing.JButton bEditCruiseCompany;
    private javax.swing.JButton bEditCruiser;
    private javax.swing.JButton bEditFlight;
    private javax.swing.JButton bEditFlightCompany;
    private javax.swing.JButton bEditLine;
    private javax.swing.JButton bEditPlane;
    private javax.swing.JButton bEditPort;
    private javax.swing.JButton bEditTrain;
    private javax.swing.JButton bEditTrainCompany;
    private javax.swing.JButton bEditTrainStation;
    private javax.swing.JButton bShowCruises;
    private javax.swing.JButton bShowFlights;
    private javax.swing.JButton bShowItineries;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lAirport;
    private javax.swing.JLabel lFlight;
    private javax.swing.JLabel lFlightCompany;
    private javax.swing.JLabel lPlane;
    private javax.swing.JPanel panelCruise;
    private javax.swing.JPanel panelPlane;
    private javax.swing.JPanel panelTrain;
    // End of variables declaration//GEN-END:variables
}
